### ISSUE TITLE
サーバー設定（History Mode対応）

### ISSUE THREAD

**Issue by gitoshiaki** [hayatetabata/kimodameshi-front#15]
Vue-RouteのようにHTML5 History Modeを使う場合は、サーバーの設定に気をつけないといけない。
https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

Expressを使ってる場合は以下が参考になるかも
https://github.com/bripkens/connect-history-api-fallback

**Comment by hayatetabata** [comment]
@gitoshiaki 
解決したはず！確認お願いします！
https://kimodameshi.herokuapp.com/lounge
